import { useEffect, useMemo, useState } from 'react';

const STORE = 'fraud-academy-v15-stable';
const pages = ['Dashboard', 'Case Queue', 'Customer 360', 'Identity Intel', 'Investigation Toolkit', 'Documents', 'Interview', 'Flags & Decision', 'Case Debrief', 'Encyclopedia'];
const icons = ['📊', '📥', '👤', '🛰️', '🧰', '📄', '🎤', '⚖️', '📖', '📚'];
const names = ['Maya Carter', 'Jordan Ellis', 'Tanya Brooks', 'Darius Hill', 'Alicia Monroe', 'Keisha Grant', 'Noah Pierce', 'Monica Wells'];
const types = ['Account Takeover', 'First-Party Fraud', 'Chargeback', 'Credit Risk', 'Application Verification', 'Email Fraud / BEC'];
const merchants = ['NorthStar Electronics', 'Velora Boutique', 'Metro Wireless', 'Luna Travel', 'Crown Payroll', 'QuickShip Market'];
const decisions = ['Approve / Pay', 'Deny', 'Partial Credit', 'Escalate', 'Request More Info'];

const typeData = {
  'Account Takeover': { summary: 'Unauthorized activity after password reset, new device login, and profile changes.', correct: 'Approve / Pay', tools: ['Login History', 'Device Fingerprint', 'IP Lookup', 'MFA History', 'Password Reset History', 'Transaction History'], questions: ['Did you approve a new device?', 'Did you receive password or MFA alerts?', 'Did anyone have access to your email or phone?'] },
  'First-Party Fraud': { summary: 'Customer claims non-receipt, but merchant evidence may support delivery.', correct: 'Deny', tools: ['Merchant Evidence', 'Shipping Records', 'Previous Claims', 'Chargeback History', 'Customer Statement'], questions: ['Did anyone at your address receive the item?', 'Did the merchant provide tracking?', 'Have you filed similar claims before?'] },
  Chargeback: { summary: 'Cardholder disputes a transaction while merchant says customer participated.', correct: 'Partial Credit', tools: ['Transaction History With Merchant', 'Prior Customer Calls', 'Order Match Review', 'Authorization Review', 'Merchant Evidence', 'Reason Code Guide'], questions: ['Do you recognize this merchant?', 'Did you contact the merchant first?', 'Does the shipping address belong to you?'] },
  'Credit Risk': { summary: 'Applicant requests credit. Income, employment, and cash flow require review.', correct: 'Escalate', tools: ['Income Verification', 'Employment Verification', 'Debt-to-Income Calculator', 'Credit Report Summary', 'Cash Flow Review', 'Bank Statements'], questions: ['What is your employer and start date?', 'Is your income gross or net?', 'Can you provide paystubs and bank statements?'] },
  'Application Verification': { summary: 'New application triggered identity, device, and document review.', correct: 'Request More Info', tools: ['SSN Verify', 'Driver License Review', 'Selfie Verification', 'Address Verification', 'Phone Verification', 'Device Fingerprint'], questions: ['Did you submit this application?', 'Can you confirm current and previous address?', 'Can you complete selfie verification?'] },
  'Email Fraud / BEC': { summary: 'Payment instructions changed after a spoofed vendor email.', correct: 'Approve / Pay', tools: ['Email Headers', 'Domain Lookup', 'Sender Analysis', 'Beneficiary Review', 'Payment Timeline', 'Wire History'], questions: ['Who requested the payment change?', 'Was the change confirmed by phone?', 'Was this beneficiary used before?'] },
};

function makeCase(i) {
  const type = types[i % types.length];
  return { id: `FA-2026-${1000 + i}`, type, customer: names[i % names.length], merchant: merchants[i % merchants.length], amount: Math.round(300 + ((i * 311) % 9500)), risk: i % 5 === 0 ? 'High' : i % 2 === 0 ? 'Medium' : 'Low', priority: i % 5 === 0 ? 'Critical' : i % 2 === 0 ? 'High' : 'Medium', address: `${7000 + i * 14} Violet Trace, Dallas, TX`, phone: `(214) 555-${String(1000 + i * 47).slice(0, 4)}`, email: `${names[i % names.length].toLowerCase().replace(' ', '.')}@examplemail.com`, dob: `19${80 + (i % 18)}-0${(i % 9) + 1}-${String((i % 27) + 1).padStart(2, '0')}`, ssn: `***-**-${String(4000 + i * 9).slice(0, 4)}`, device: `DEV-${90000 + i * 41}`, ip: `172.${16 + i}.${30 + i}.${40 + i}`, opened: `2026-07-${String((i % 28) + 1).padStart(2, '0')}`, ...typeData[type] };
}
function initial() { return { page: 'Dashboard', cases: Array.from({ length: 24 }, (_, i) => makeCase(i)), selectedId: 'FA-2026-1000', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', completed: [], lastClosed: null, toolResult: null, intelResult: null }; }
function load() { try { return JSON.parse(localStorage.getItem(STORE)) || initial(); } catch { return initial(); } }

export default function App() {
  const [s, setS] = useState(load);
  const c = useMemo(() => s.cases.find(x => x.id === s.selectedId) || s.cases[0] || s.lastClosed, [s]);
  useEffect(() => localStorage.setItem(STORE, JSON.stringify(s)), [s]);
  const patch = (x) => setS(v => ({ ...v, ...x }));
  const page = (p) => patch({ page: p });
  const mark = (x) => setS(v => ({ ...v, reviewed: [...new Set([...v.reviewed, x])] }));
  const flag = (kind, text) => setS(v => ({ ...v, flags: [...v.flags, { kind, text, at: new Date().toLocaleTimeString() }] }));
  const doc = (d) => setS(v => ({ ...v, docs: [...new Set([...v.docs, d])] }));
  const select = (id) => patch({ selectedId: id, page: 'Case Queue', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', toolResult: null, intelResult: null });
  const complete = () => {
    if (!c || !s.decision) return;
    const score = Math.min(100, s.flags.length * 10 + s.reviewed.length * 5 + s.docs.length * 7 + s.interview.length * 4 + (s.decision === c.correct ? 20 : 0));
    const closed = { ...c, decision: s.decision, score, flags: s.flags, docs: s.docs, notes: s.notes, interview: s.interview, closedAt: new Date().toLocaleString() };
    const remaining = s.cases.filter(x => x.id !== c.id);
    setS({ ...s, cases: remaining, selectedId: remaining[0]?.id || '', completed: [closed, ...s.completed], lastClosed: closed, page: 'Case Debrief', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', toolResult: null, intelResult: null });
  };
  const props = { s, c, patch, page, mark, flag, doc, select, complete };
  return <div className="app"><aside className="side"><div className="brand"><div className="logo">🕵🏽</div><div><h1>Fraud Academy</h1><p>Cozy Detective Command Center</p></div></div><nav className="nav">{pages.map((p, i) => <button key={p} className={s.page === p ? 'active' : ''} onClick={() => page(p)}>{icons[i]} {p}</button>)}</nav><div className="card mini"><b>🕒 SLA Clock</b><p className="muted">{c ? `${c.priority} priority case` : 'Queue cleared'}</p><div className="progress"><div className="bar" style={{ width: c?.priority === 'Critical' ? '84%' : '48%' }} /></div></div></aside><main className="main"><div className="top"><div><h2>{s.page}</h2><div className="muted">Find flags, tag evidence, make a decision, then debrief.</div></div><span className="pill">💜 v15 Command Center</span></div>{s.page === 'Dashboard' && <Dashboard {...props} />}{s.page === 'Case Queue' && <Queue {...props} />}{s.page === 'Customer 360' && <Customer {...props} />}{s.page === 'Identity Intel' && <Intel {...props} />}{s.page === 'Investigation Toolkit' && <Toolkit {...props} />}{s.page === 'Documents' && <Documents {...props} />}{s.page === 'Interview' && <Interview {...props} />}{s.page === 'Flags & Decision' && <Decision {...props} />}{s.page === 'Case Debrief' && <Debrief {...props} />}{s.page === 'Encyclopedia' && <Encyclopedia />}</main></div>;
}
function Dashboard({ s, c, page, patch }) { return <div className="grid"><div className="grid three"><Stat label="Open Cases" val={s.cases.length} /><Stat label="Completed" val={s.completed.length} /><Stat label="Current" val={c?.id || 'None'} /></div><div className="grid cols"><div className="card"><h3>💜 Cozy Detective Theme</h3><p>v15 brings back the old command-center flow: case queue, customer 360, identity intel, toolkit, documents, interview, flags, decision, and debrief.</p><div className="row"><button className="btn" onClick={() => page('Case Queue')}>Open Queue</button><button className="btn secondary" onClick={() => patch(initial())}>Reset Training</button></div></div><div className="card"><h3>🎲 Random Case Event</h3><p className="muted">Add a surprise evidence update to your notes.</p><button className="btn gold" onClick={() => patch({ notes: [...s.notes, 'Random event: new merchant packet and customer statement arrived.'] })}>Trigger Event</button></div></div>{s.completed.length > 0 && <div className="card"><h3>✅ Recently Completed</h3>{s.completed.slice(0, 5).map(x => <div className="result good" key={x.id}><b>{x.id}</b> · {x.type}<br /><span className="muted">Decision: {x.decision} · Score: {x.score}%</span></div>)}</div>}</div>; }
function Stat({ label, val }) { return <div className="card"><div className="muted">{label}</div><div className="stat">{val}</div></div>; }
function Queue({ s, c, select, page }) { if (!s.cases.length) return <div className="card"><h3>🎉 Queue Cleared</h3><p>All cases are complete.</p></div>; return <div className="split"><div className="card"><h3>📥 Claim Queue ({s.cases.length})</h3>{s.cases.map(x => <button className={c?.id === x.id ? 'case active' : 'case'} key={x.id} onClick={() => select(x.id)}><div className="case-title"><span>{x.id}</span><span className={`tag risk-${x.risk.toLowerCase()}`}>{x.priority}</span></div><div>{x.customer}</div><div className="muted mini">{x.type} · ${x.amount.toLocaleString()}</div></button>)}</div><div className="card"><h3>📁 Full Claim File</h3><Claim c={c} /><div className="row"><button className="btn" onClick={() => page('Customer 360')}>Customer 360</button><button className="btn secondary" onClick={() => page('Investigation Toolkit')}>Toolkit</button></div></div></div>; }
function Claim({ c }) { if (!c) return <p>No case selected.</p>; return <><KV k="Claim Type" v={c.type} /><KV k="Customer" v={c.customer} /><KV k="Amount" v={`$${c.amount.toLocaleString()}`} /><KV k="Merchant" v={c.merchant} /><KV k="Opened" v={c.opened} /><KV k="Summary" v={c.summary} /><KV k="Training Answer" v={c.correct} /></>; }
function Customer({ c, mark }) { useEffect(() => mark('Customer 360'), []); return <div className="grid cols"><div className="card"><h3>👤 Customer 360</h3><div className="row"><div className="logo">{c.customer[0]}</div><div><h2>{c.customer}</h2><span className={`tag risk-${c.risk.toLowerCase()}`}>{c.risk} Risk</span></div></div><KV k="DOB" v={c.dob} /><KV k="SSN" v={c.ssn} /><KV k="Address" v={c.address} /><KV k="Email" v={c.email} /><KV k="Phone" v={c.phone} /></div><div className="card"><h3>💳 Banking Relationship</h3><KV k="Checking" v={`****${c.id.slice(-4)} · $${(1800 + c.amount / 8).toFixed(2)}`} /><KV k="Device" v={c.device} /><KV k="IP" v={c.ip} /><div className={`result ${c.risk === 'High' ? 'bad' : 'good'}`}>{c.risk === 'High' ? 'Shared device or recent profile change found.' : 'Profile appears stable with normal history.'}</div></div></div>; }
function Intel({ c, s, patch, mark, flag }) { useEffect(() => mark('Identity Intel'), []); const result = s.intelResult; const run = (type) => patch({ intelResult: { type, value: type === 'SSN' ? c.ssn : type === 'Phone' ? c.phone : type === 'Email' ? c.email : type === 'Device' ? c.device : c.address } }); return <div className="grid cols"><div className="card"><h3>🛰️ Identity Intel Workspace</h3><p className="muted">Search fictional identity records and tag what matters.</p><div className="tools">{['SSN', 'Phone', 'Email', 'Address', 'Device', 'IP'].map(x => <button className="tool" key={x} onClick={() => run(x)}>🔎 {x} Search</button>)}</div></div><div className="card"><h3>🔎 Results</h3>{result ? <div className={`result ${c.risk === 'High' ? 'warn' : 'good'}`}><KV k="Search Type" v={result.type} /><KV k="Value" v={result.value} /><KV k="Identity Confidence" v={c.risk === 'High' ? '62%' : '94%'} /><KV k="Linked Records" v={c.risk === 'High' ? 'Shared identifiers found on unrelated profiles.' : 'No unrelated linked profiles.'} /><div className="row"><button className="btn green" onClick={() => flag('green', `${result.type} supports identity`)}>Tag Green</button><button className="btn red" onClick={() => flag('red', `${result.type} has suspicious identity links`)}>Tag Red</button></div></div> : <p className="muted">Run a search to see records.</p>}</div></div>; }
function Toolkit({ c, s, patch, mark, flag }) { useEffect(() => mark('Investigation Toolkit'), []); const run = (tool) => patch({ toolResult: tool }); return <div className="grid cols"><div className="card"><h3>🧰 Investigation Toolkit</h3><p className="muted">Tools change by claim type: <b>{c.type}</b>.</p><div className="tools">{(c.tools || []).map(t => <button className="tool" key={t} onClick={() => run(t)}>{toolIcon(t)} {t}</button>)}</div></div><div className="card"><h3>Tool Results</h3>{s.toolResult ? <ToolResult c={c} tool={s.toolResult} flag={flag} /> : <p className="muted">Pick a tool to search detailed fictional records.</p>}</div></div>; }
function ToolResult({ c, tool, flag }) { return <div className={c.risk === 'High' ? 'result warn' : 'result good'}><h3>{tool}</h3><KV k="Record Reviewed" v={`${tool} for ${c.customer}`} /><KV k="Finding" v={c.risk === 'High' ? 'Recent change, mismatch, or shared identifier requires review.' : 'Record generally matches expected customer behavior.'} /><KV k="Investigator Prompt" v="Compare this with Customer 360, documents, interview, and claim timeline." /><div className="row"><button className="btn green" onClick={() => flag('green', `${tool}: supports claim`)}>Tag Green</button><button className="btn red" onClick={() => flag('red', `${tool}: suspicious finding`)}>Tag Red</button></div></div>; }
function Documents({ c, s, doc, flag, mark }) { useEffect(() => mark('Documents'), []); const docs = ['Driver License', 'Bank Statement', 'Paystub', 'Police Report', 'Merchant Receipt', 'Proof of Delivery', 'Business License']; return <div className="grid cols"><div className="card"><h3>📄 Request Documents</h3>{docs.map(d => <button className="case" key={d} onClick={() => doc(d)}>📄 {d}</button>)}</div><div className="card"><h3>📂 Document Viewer</h3>{s.docs.length ? s.docs.map(d => <div className="doc" key={d}><h3>{d}</h3><KV k="Customer" v={c.customer} /><KV k="Reference" v={`${c.id}-${d.slice(0, 3).toUpperCase()}`} /><KV k="Signal" v={c.risk === 'High' ? 'Contains an inconsistency to review.' : 'Mostly consistent with profile.'} /><div className="row"><button className="btn green" onClick={() => flag('green', `${d}: supports record`)}>Tag Green</button><button className="btn red" onClick={() => flag('red', `${d}: inconsistency found`)}>Tag Red</button></div></div>) : <p className="muted">No documents requested yet.</p>}</div></div>; }
function Interview({ c, s, patch, mark, flag }) { useEffect(() => mark('Interview'), []); const ask = (q) => patch({ interview: [...s.interview, { q, a: answer(c, q) }] }); return <div className="grid cols"><div className="card"><h3>🎤 Customer Interview</h3>{c.questions.map(q => <button className="case" key={q} onClick={() => ask(q)}>{q}</button>)}</div><div className="card"><h3>Transcript</h3>{s.interview.length ? s.interview.map(x => <div key={x.q}><div className="bubble inv"><b>Investigator:</b> {x.q}</div><div className="bubble cust"><b>Customer:</b> {x.a}</div></div>) : <p className="muted">No questions asked yet.</p>}<div className="row"><button className="btn green" onClick={() => flag('green', 'Interview supports claim')}>Tag Green</button><button className="btn red" onClick={() => flag('red', 'Interview has inconsistencies')}>Tag Red</button></div></div></div>; }
function Decision({ c, s, patch, complete }) { return <div className="grid cols"><div className="card"><h3>⚖️ Flags & Decision</h3>{s.flags.length ? s.flags.map((f, i) => <div className={`result ${f.kind === 'red' ? 'bad' : 'good'}`} key={i}><b>{f.kind === 'red' ? '🔴' : '🟢'} {f.text}</b><br /><span className="muted">{f.at}</span></div>) : <p className="muted">No flags tagged yet.</p>}</div><div className="card"><h3>Final Decision</h3>{decisions.map(d => <button key={d} className={s.decision === d ? 'choice active' : 'choice'} onClick={() => patch({ decision: d })}>{d}</button>)}<button className="btn" disabled={!s.decision} onClick={complete}>Complete Case</button><p className="muted">Training answer: {c?.correct}</p></div></div>; }
function Debrief({ s }) { const d = s.lastClosed; if (!d) return <div className="card"><h3>📖 Case Debrief</h3><p>Complete a case to generate debrief.</p></div>; return <div className="grid"><div className="card"><h3>📖 Case Debrief: {d.id}</h3><KV k="Claim Type" v={d.type} /><KV k="Your Decision" v={d.decision} /><KV k="Recommended" v={d.correct} /><KV k="Score" v={`${d.score}%`} /><p>{d.summary}</p></div><div className="grid cols"><div className="card"><h3>Evidence You Tagged</h3>{d.flags.length ? d.flags.map((f, i) => <div className={`result ${f.kind === 'red' ? 'bad' : 'good'}`} key={i}>{f.text}</div>) : <p>No flags were tagged.</p>}</div><div className="card"><h3>Case Notes</h3>{d.notes.length ? d.notes.map((n, i) => <div className="result" key={i}>{n}</div>) : <p>No notes captured.</p>}</div></div></div>; }
function Encyclopedia() { return <div className="grid cols"><div className="card"><h3>📚 Fraud Claim Types</h3>{types.map(t => <div className="result" key={t}><b>{t}</b><p className="muted">{typeData[t].summary}</p></div>)}</div><div className="card"><h3>Investigator Rules</h3><p>Use Customer 360, run Identity Intel, search the claim-specific toolkit, request documents, interview the customer, tag red and green flags, then make your decision.</p></div></div>; }
function KV({ k, v }) { return <div className="kv"><b>{k}</b><span>{v}</span></div>; }
function toolIcon(t) { if (t.includes('Device') || t.includes('IP') || t.includes('Email')) return '🌐'; if (t.includes('Document') || t.includes('Evidence') || t.includes('Delivery')) return '📄'; if (t.includes('Credit') || t.includes('Income') || t.includes('Debt')) return '📊'; return '🔍'; }
function answer(c, q) { return c.risk === 'High' ? `I'm not fully sure. I noticed something odd around the same time as the claim. (${q})` : `That matches my normal activity and I can provide supporting details. (${q})`; }
