import { useEffect, useMemo, useState } from 'react';
import { getToolkitRecord } from './toolkitRecords.js';
import { getAICoachReview } from './aiCoach.js';
import { getInterviewAnswer } from './interviewScripts.js';
import { getDocumentReport } from './documentReports.js';

const STORE = 'fraud-academy-v15-toolkit-upgrade';
const pages = ['Dashboard', 'Case Queue', 'Customer 360', 'Identity Intel', 'Investigation Toolkit', 'Documents', 'Interview', 'Flags & Decision', 'Case Debrief', 'Encyclopedia'];
const icons = ['📊', '📥', '👤', '🛰️', '🧰', '📄', '🎤', '⚖️', '📖', '📚'];
const names = ['Maya Carter', 'Jordan Ellis', 'Tanya Brooks', 'Darius Hill', 'Alicia Monroe', 'Keisha Grant'];
const types = ['Account Takeover', 'First-Party Fraud', 'Chargeback', 'Credit Risk', 'Application Verification', 'Email Fraud / BEC'];
const parties = ['NorthStar Electronics', 'Velora Boutique', 'Metro Wireless', 'Luna Travel', 'Crown Payroll', 'QuickShip Market'];
const decisions = ['Approve / Pay', 'Deny', 'Partial Credit', 'Escalate', 'Request More Info'];
const details = {
  'Account Takeover': { correct: 'Approve / Pay', summary: 'Customer reports activity after profile changes and a new digital access event.', tools: ['Login History', 'Session History', 'Device Fingerprint', 'IP Lookup', 'MFA History', 'Password Reset History', 'Transaction History'], questions: ['Did you approve a new device?', 'Did you receive profile change alerts?', 'Did anyone have access to your phone or email?'] },
  'First-Party Fraud': { correct: 'Deny', summary: 'Customer claims non-receipt, but merchant evidence may support delivery.', tools: ['Merchant Evidence', 'Shipping Records', 'Previous Claims', 'Chargeback History', 'Customer Statement'], questions: ['Did anyone at your address receive the item?', 'Did the merchant provide tracking?', 'Have you filed similar claims before?'] },
  'Chargeback': { correct: 'Partial Credit', summary: 'Cardholder disputes a transaction while merchant says customer participated.', tools: ['Transaction History With Merchant', 'Prior Customer Calls', 'Order Match Review', 'Authorization Review', 'Merchant Evidence', 'Reason Code Guide'], questions: ['Do you recognize this merchant?', 'Did you contact the merchant first?', 'Does the shipping address belong to you?'] },
  'Credit Risk': { correct: 'Escalate', summary: 'Applicant requests credit. Income, work history, cash flow, and obligations need review.', tools: ['Income Verification', 'Employment Verification', 'Debt-to-Income Calculator', 'Credit Report Summary', 'Cash Flow Review', 'Bank Statements'], questions: ['What is your employer and start date?', 'Is your income gross or net?', 'Can you provide support records?'] },
  'Application Verification': { correct: 'Request More Info', summary: 'New application triggered profile, document, and device review.', tools: ['Profile Verify', 'Driver License Review', 'Selfie Verification', 'Address Verification', 'Phone Verification', 'Device Fingerprint'], questions: ['Did you submit this application?', 'Can you confirm current and previous address?', 'Can you complete selfie verification?'] },
  'Email Fraud / BEC': { correct: 'Approve / Pay', summary: 'Payment instructions changed after a spoofed vendor-style email.', tools: ['Email Headers', 'Domain Lookup', 'Sender Analysis', 'Beneficiary Review', 'Payment Timeline', 'Wire History'], questions: ['Who requested the payment change?', 'Was the change confirmed by phone?', 'Was this beneficiary used before?'] }
};
function makeCase(i) { const type = types[i % types.length]; return { id: `FA-2026-${1000 + i}`, type, customer: names[i % names.length], merchant: parties[i % parties.length], amount: Math.round(300 + ((i * 311) % 9500)), risk: i % 5 === 0 ? 'High' : i % 2 === 0 ? 'Medium' : 'Low', priority: i % 5 === 0 ? 'Critical' : i % 2 === 0 ? 'High' : 'Medium', address: `${7000 + i * 14} Violet Trace, Dallas, TX`, phone: `(214) 555-${String(1000 + i * 47).slice(0, 4)}`, email: `${names[i % names.length].toLowerCase().replace(' ', '.')}@examplemail.com`, dob: `198${i % 10}-0${(i % 9) + 1}-${String((i % 27) + 1).padStart(2, '0')}`, profileId: `PROFILE-${4000 + i * 9}`, device: `DEV-${90000 + i * 41}`, ip: `172.${16 + i}.${30 + i}.${40 + i}`, opened: `2026-07-${String((i % 28) + 1).padStart(2, '0')}`, ...details[type] }; }
function initial() { return { page: 'Dashboard', cases: Array.from({ length: 24 }, (_, i) => makeCase(i)), selectedId: 'FA-2026-1000', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', completed: [], lastClosed: null, toolResult: null, intelResult: null }; }
function load() { try { return JSON.parse(localStorage.getItem(STORE)) || initial(); } catch { return initial(); } }
export default function App() {
  const [s, setS] = useState(load); const c = useMemo(() => s.cases.find(x => x.id === s.selectedId) || s.cases[0] || s.lastClosed, [s]); useEffect(() => localStorage.setItem(STORE, JSON.stringify(s)), [s]);
  const patch = x => setS(v => ({ ...v, ...x })); const page = p => patch({ page: p }); const mark = x => setS(v => ({ ...v, reviewed: [...new Set([...v.reviewed, x])] })); const flag = (kind, text) => setS(v => ({ ...v, flags: [...v.flags, { kind, text, at: new Date().toLocaleTimeString() }] })); const addDoc = d => setS(v => ({ ...v, docs: [...new Set([...v.docs, d])] })); const openDocs = docs => setS(v => ({ ...v, docs: [...new Set([...v.docs, ...docs])], page: 'Documents' }));
  const select = id => patch({ selectedId: id, page: 'Case Queue', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', toolResult: null, intelResult: null });
  const complete = () => { if (!c || !s.decision) return; const score = Math.min(100, s.flags.length * 10 + s.reviewed.length * 5 + s.docs.length * 7 + s.interview.length * 4 + (s.decision === c.correct ? 20 : 0)); const closed = { ...c, decision: s.decision, score, flags: s.flags, docs: s.docs, notes: s.notes, interview: s.interview, closedAt: new Date().toLocaleString() }; const remaining = s.cases.filter(x => x.id !== c.id); setS({ ...s, cases: remaining, selectedId: remaining[0]?.id || '', completed: [closed, ...s.completed], lastClosed: closed, page: 'Case Debrief', notes: [], flags: [], docs: [], interview: [], reviewed: [], decision: '', toolResult: null, intelResult: null }); };
  const props = { s, c, patch, page, mark, flag, addDoc, openDocs, select, complete };
  return <div className="app"><aside className="side"><div className="brand"><div className="logo">🕵🏽</div><div><h1>Fraud Academy</h1><p>Cozy Detective Command Center</p></div></div><nav className="nav">{pages.map((p, i) => <button key={p} className={s.page === p ? 'active' : ''} onClick={() => page(p)}>{icons[i]} {p}</button>)}</nav><div className="card mini"><b>🕒 SLA Clock</b><p className="muted">{c ? `${c.priority} priority case` : 'Queue cleared'}</p><div className="progress"><div className="bar" style={{ width: c?.priority === 'Critical' ? '84%' : '48%' }} /></div></div></aside><main className="main"><div className="top"><div><h2>{s.page}</h2><div className="muted">Find flags, tag evidence, make a decision, then debrief.</div></div><span className="pill">💜 v15 Command Center</span></div>{s.page === 'Dashboard' && <Dashboard {...props} />}{s.page === 'Case Queue' && <Queue {...props} />}{s.page === 'Customer 360' && <Customer {...props} />}{s.page === 'Identity Intel' && <Intel {...props} />}{s.page === 'Investigation Toolkit' && <Toolkit {...props} />}{s.page === 'Documents' && <Documents {...props} />}{s.page === 'Interview' && <Interview {...props} />}{s.page === 'Flags & Decision' && <Decision {...props} />}{s.page === 'Case Debrief' && <Debrief {...props} />}{s.page === 'Encyclopedia' && <Encyclopedia />}</main></div>;
}
function Dashboard({ s, c, page, patch }) { return <div className="grid"><div className="grid three"><Stat label="Open Cases" val={s.cases.length} /><Stat label="Completed" val={s.completed.length} /><Stat label="Current" val={c?.id || 'None'} /></div><div className="grid cols"><div className="card"><h3>💜 Toolkit Upgrade Active</h3><p>Toolkit results now show detailed fictional records, evidence signals, related documents, and next steps.</p><div className="row"><button className="btn" onClick={() => page('Case Queue')}>Open Queue</button><button className="btn secondary" onClick={() => patch(initial())}>Reset Training</button></div></div><div className="card"><h3>🎲 Random Case Event</h3><button className="btn gold" onClick={() => patch({ notes: [...s.notes, 'Random event: new evidence packet arrived.'] })}>Trigger Event</button></div></div></div>; }
function Stat({ label, val }) { return <div className="card"><div className="muted">{label}</div><div className="stat">{val}</div></div>; }
function Queue({ s, c, select, page }) { if (!s.cases.length) return <div className="card"><h3>🎉 Queue Cleared</h3><p>All cases are complete.</p></div>; return <div className="split"><div className="card"><h3>📥 Claim Queue ({s.cases.length})</h3>{s.cases.map(x => <button className={c?.id === x.id ? 'case active' : 'case'} key={x.id} onClick={() => select(x.id)}><div className="case-title"><span>{x.id}</span><span className={`tag risk-${x.risk.toLowerCase()}`}>{x.priority}</span></div><div>{x.customer}</div><div className="muted mini">{x.type} · ${x.amount.toLocaleString()}</div></button>)}</div><div className="card"><h3>📁 Full Claim File</h3><Claim c={c} /><div className="row"><button className="btn" onClick={() => page('Customer 360')}>Customer 360</button><button className="btn secondary" onClick={() => page('Investigation Toolkit')}>Toolkit</button></div></div></div>; }
function Claim({ c }) { if (!c) return <p>No case selected.</p>; return <><KV k="Claim Type" v={c.type} /><KV k="Customer" v={c.customer} /><KV k="Amount" v={`$${c.amount.toLocaleString()}`} /><KV k="Merchant / Party" v={c.merchant} /><KV k="Opened" v={c.opened} /><KV k="Summary" v={c.summary} /><KV k="Training Answer" v={c.correct} /></>; }
function Customer({ c, mark, flag, openDocs }) { useEffect(() => mark('Customer 360'), []); const high = c.risk === 'High'; return <div className="grid cols"><div className="card"><h3>👤 Customer 360</h3><div className="row"><div className="logo">{c.customer[0]}</div><div><h2>{c.customer}</h2><span className={`tag risk-${c.risk.toLowerCase()}`}>{c.risk} Risk</span></div></div><KV k="DOB" v={c.dob} /><KV k="Profile Ref" v={c.profileId} /><KV k="Address" v={c.address} /><KV k="Email" v={c.email} /><KV k="Phone" v={c.phone} /><KV k="Customer Since" v="2019" /><KV k="Prior Claims" v={high ? '2 prior digital-access claims and 1 card dispute' : 'No recent fraud claims'} /></div><div className="card"><h3>🔒 Account History</h3><div className={`result ${high ? 'bad' : 'good'}`}><b>Profile Change Summary</b><KV k="Password" v={high ? 'Changed after new-device login' : 'No recent change'} /><KV k="Recovery Email" v={high ? 'Updated during same session' : 'No change in last 90 days'} /><KV k="Phone" v={high ? 'Changed before OTP delivery' : 'Trusted phone unchanged'} /><KV k="MFA Device" v={high ? 'New SMS route enrolled' : 'Existing trusted MFA route'} /><KV k="Security Questions" v={high ? 'Updated after password reset' : 'No recent update'} /></div><h3>Known Devices</h3><KV k="Primary Device" v={high ? 'iPhone 15 - trusted before claim' : `${c.device} - trusted`} /><KV k="New Device" v={high ? `${c.device} - first seen during claim` : 'None detected'} /><h3>Known Locations</h3><KV k="Normal Region" v="Dallas, TX" /><KV k="Current Signal" v={high ? 'New region or proxy-style signal' : 'Normal customer region'} /><div className="row"><button className="btn secondary" onClick={() => openDocs(['Profile Change History'])}>Open Profile Change Report</button><button className="btn red" onClick={() => flag('red', 'Customer 360: profile changes occurred before loss')}>Tag Profile Risk</button></div></div></div>; }
function Intel({ c, s, patch, mark, flag }) { useEffect(() => mark('Identity Intel'), []); const run = type => patch({ intelResult: { type, value: type === 'Profile' ? c.profileId : type === 'Phone' ? c.phone : type === 'Email' ? c.email : type === 'Device' ? c.device : c.address } }); return <div className="grid cols"><div className="card"><h3>🛰️ Identity Intel Workspace</h3><p className="muted">Search fictional profile records and tag what matters.</p><div className="tools">{['Profile', 'Phone', 'Email', 'Address', 'Device', 'IP'].map(x => <button className="tool" key={x} onClick={() => run(x)}>🔎 {x} Search</button>)}</div></div><div className="card"><h3>🔎 Results</h3>{s.intelResult ? <div className={`result ${c.risk === 'High' ? 'warn' : 'good'}`}><KV k="Search Type" v={s.intelResult.type} /><KV k="Value" v={s.intelResult.value} /><KV k="Confidence" v={c.risk === 'High' ? '62%' : '94%'} /><KV k="Linked Records" v={c.risk === 'High' ? 'Shared or recent identifiers found.' : 'No unrelated profile links.'} /><div className="row"><button className="btn green" onClick={() => flag('green', `${s.intelResult.type} supports profile`) }>Tag Green</button><button className="btn red" onClick={() => flag('red', `${s.intelResult.type} needs review`) }>Tag Red</button></div></div> : <p className="muted">Run a search to see records.</p>}</div></div>; }
function Toolkit({ c, s, patch, mark, flag, openDocs }) { useEffect(() => mark('Investigation Toolkit'), []); return <div className="grid cols"><div className="card"><h3>🧰 Investigation Toolkit</h3><p className="muted">Tools change by claim type: <b>{c.type}</b>. Results now include fictional records, evidence signals, documents, and next steps.</p><div className="tools">{(c.tools || []).map(t => <button className={s.toolResult === t ? 'tool active' : 'tool'} key={t} onClick={() => patch({ toolResult: t })}>{toolIcon(t)} {t}</button>)}</div></div><div className="card"><h3>Tool Results</h3>{s.toolResult ? <ToolResult c={c} tool={s.toolResult} flag={flag} openDocs={openDocs} /> : <p className="muted">Pick a tool to search detailed fictional records.</p>}</div></div>; }
function ToolResult({ c, tool, flag, openDocs }) { const r = getToolkitRecord(tool, c); return <div className={r.level === 'red' ? 'result bad' : r.level === 'yellow' ? 'result warn' : 'result good'}><h3>{r.title}</h3><p>{r.summary}</p>{r.rows.map(([k, v]) => <KV key={k} k={k} v={v} />)}<h3>Evidence Signals</h3>{r.signals.map(x => <div className="result" key={x}>{x}</div>)}<h3>Related Documents</h3>{r.docs.map(d => <button className="case" key={d} onClick={() => openDocs([d])}>📄 Open {d}</button>)}<h3>Next Steps</h3>{r.next.map(x => <div className="result" key={x}>{x}</div>)}<div className="row"><button className="btn green" onClick={() => flag('green', `${tool}: ${r.signals[0]}`)}>Tag Green</button><button className="btn red" onClick={() => flag('red', `${tool}: ${r.signals[0]}`)}>Tag Red</button></div></div>; }
function Documents({ c, s, addDoc, flag, mark }) { useEffect(() => mark('Documents'), []); const docs = ['Driver License', 'Bank Statement', 'Paystub', 'Police Report', 'Merchant Receipt', 'Proof of Delivery', 'Business License', 'Email Header', 'Login Timeline', 'Profile Change History', 'Session History', 'Device Fingerprint Report', 'Authorization Log', 'Order Match Sheet', 'Payment Timeline', 'Carrier Timeline', 'Prior Claims Memo']; return <div className="grid cols"><div className="card"><h3>📄 Request Documents</h3>{docs.map(d => <button className="case" key={d} onClick={() => addDoc(d)}>📄 {d}</button>)}</div><div className="card"><h3>📂 Document Viewer</h3>{s.docs.length ? s.docs.map(d => { const report = getDocumentReport(d, c); return <div className="doc" key={d}><h3>{d}</h3><KV k="Customer" v={c.customer} /><KV k="Reference" v={`${c.id}-${d.slice(0, 3).toUpperCase()}`} /><KV k="Claim Type" v={c.type} /><KV k="Status" v={report.status} /><KV k="Confidence" v={report.confidence} /><h3>Report Details</h3>{report.sections.map(([k, v]) => <KV key={k} k={k} v={v} />)}<h3>Investigator Notes</h3>{report.notes.map(x => <div className="result" key={x}>{x}</div>)}<h3>Training Tip</h3><div className="result good">{report.tip}</div><div className="row"><button className="btn green" onClick={() => flag('green', `${d}: supports record`)}>Tag Green</button><button className="btn red" onClick={() => flag('red', `${d}: needs review`)}>Tag Red</button></div></div>; }) : <p className="muted">No documents requested yet.</p>}</div></div>; }
function Interview({ c, s, patch, mark, flag }) { useEffect(() => mark('Interview'), []); const ask = q => { const prior = s.interview.filter(x => x.q === q).length; const reply = getInterviewAnswer(c, q, prior); patch({ interview: [...s.interview, { q, a: reply.answer, tone: reply.tone, credibility: reply.credibility, clue: reply.clue }] }); }; const last = s.interview[s.interview.length - 1]; return <div className="grid cols"><div className="card"><h3>🎤 Customer Interview</h3>{last && <div className="result warn"><KV k="Tone" v={last.tone} /><KV k="Credibility" v={`${last.credibility}%`} /><KV k="New Clue" v={last.clue} /></div>}{c.questions.map(q => <button className="case" key={q} onClick={() => ask(q)}>{q}</button>)}</div><div className="card"><h3>Transcript</h3>{s.interview.length ? s.interview.map((x, i) => <div key={`${x.q}-${i}`}><div className="bubble inv"><b>Investigator:</b> {x.q}</div><div className="bubble cust"><b>Customer:</b> {x.a}</div>{x.clue && <div className="result warn"><b>Interview clue:</b> {x.clue}</div>}</div>) : <p className="muted">No questions asked yet.</p>}<div className="row"><button className="btn green" onClick={() => flag('green', 'Interview supports claim')}>Tag Green</button><button className="btn red" onClick={() => flag('red', 'Interview has inconsistencies')}>Tag Red</button></div></div></div>; }
function Decision({ c, s, patch, complete }) { return <div className="grid cols"><div className="card"><h3>⚖️ Flags & Decision</h3>{s.flags.length ? s.flags.map((f, i) => <div className={`result ${f.kind === 'red' ? 'bad' : 'good'}`} key={i}><b>{f.kind === 'red' ? '🔴' : '🟢'} {f.text}</b><br /><span className="muted">{f.at}</span></div>) : <p className="muted">No flags tagged yet.</p>}</div><div className="card"><h3>Final Decision</h3>{decisions.map(d => <button key={d} className={s.decision === d ? 'choice active' : 'choice'} onClick={() => patch({ decision: d })}>{d}</button>)}<button className="btn" disabled={!s.decision} onClick={complete}>Complete Case</button><p className="muted">Training answer: {c?.correct}</p></div></div>; }
function Debrief({ s }) { const d = s.lastClosed; if (!d) return <div className="card"><h3>📖 Case Debrief</h3><p>Complete a case to generate debrief.</p></div>; const coach = getAICoachReview(d); return <div className="grid"><div className="card"><h3>📖 Case Debrief: {d.id}</h3><KV k="Claim Type" v={d.type} /><KV k="Your Decision" v={d.decision} /><KV k="Recommended" v={d.correct} /><KV k="Score" v={`${d.score}%`} /><p>{d.summary}</p></div><div className="card"><h3>🤖 AI Coach Review</h3><div className={`result ${coach.tone}`}><b>{coach.headline}</b><KV k="Coach Verdict" v={coach.verdict} /><KV k="Confidence" v={`${coach.confidence}%`} /></div><h3>Why</h3>{coach.why.map(x => <div className="result" key={x}>{x}</div>)}<h3>What To Review</h3>{coach.missed.length ? coach.missed.map(x => <div className="result warn" key={x}>{x}</div>) : <div className="result good">You covered the major evidence categories for this case.</div>}<h3>Think Like a Senior Investigator</h3><div className="result good">{coach.seniorTip}</div><h3>Next Practice Steps</h3>{coach.next.map(x => <div className="result" key={x}>{x}</div>)}</div><div className="grid cols"><div className="card"><h3>Evidence You Tagged</h3>{d.flags.length ? d.flags.map((f, i) => <div className={`result ${f.kind === 'red' ? 'bad' : 'good'}`} key={i}>{f.text}</div>) : <p>No flags were tagged.</p>}</div><div className="card"><h3>Documents Reviewed</h3>{d.docs.length ? d.docs.map(x => <div className="result" key={x}>{x}</div>) : <p>No documents reviewed.</p>}</div></div></div>; }
function Encyclopedia() { return <div className="grid cols"><div className="card"><h3>📚 Fraud Claim Types</h3>{types.map(t => <div className="result" key={t}><b>{t}</b><p className="muted">{details[t].summary}</p></div>)}</div><div className="card"><h3>Investigator Rules</h3><p>Use Customer 360, run Identity Intel, search claim-specific toolkit records, open documents, interview the customer, tag flags, then decide.</p></div></div>; }
function KV({ k, v }) { return <div className="kv"><b>{k}</b><span>{v}</span></div>; }
function toolIcon(t) { if (t.includes('Device') || t.includes('IP') || t.includes('Email')) return '🌐'; if (t.includes('Evidence') || t.includes('Shipping')) return '📄'; if (t.includes('Credit') || t.includes('Income') || t.includes('Debt') || t.includes('Cash')) return '📊'; return '🔍'; }
function docSignal(d, c) { return c.risk === 'High' ? `${d} contains a mismatch, missing support, or timeline issue to review.` : `${d} mostly matches the profile and claim timeline, but should be compared with other evidence.`; }
