const reportDetails = {
  'Driver License': {
    status: 'Identity Document Review',
    confidence: '86%',
    sections: [
      ['Front Image', 'Name, DOB, and document number are readable in the submitted image.'],
      ['Back Image', 'Barcode is present and matches the front-side identity fields.'],
      ['Expiration', 'Document is current based on the visible expiration date.'],
      ['Address Match', 'Address mostly matches Customer 360; compare any apartment/unit differences.'],
      ['Security Features', 'No obvious alteration signals in the fictional document review.'],
    ],
    notes: ['Use Driver License with Selfie Verification and Address Verification before clearing an application.', 'A readable ID is supportive, but it does not prove the person controlling the device is the applicant.'],
    tip: 'Driver License review is strongest when the ID, selfie, application device, and Customer 360 profile all point to the same person.',
  },
  'Bank Statement': {
    status: 'Financial Capacity Review',
    confidence: '78%',
    sections: [
      ['Statement Period', 'Recent statement covers the claimed income and cash-flow window.'],
      ['Direct Deposits', 'Deposit pattern appears regular but should be compared with paystub timing.'],
      ['NSF / Overdrafts', 'Review for repeated negative balances or returned items.'],
      ['Large Transfers', 'One-time transfers need source-of-funds context before credit approval.'],
      ['Name / Address', 'Account holder details should match application and Customer 360.'],
    ],
    notes: ['Compare deposits with Paystub and Employment Verification.', 'Do not treat screenshots as final support when a full statement or bank feed is required.'],
    tip: 'Bank statements answer whether money behavior supports the story. Look for recurring deposits, balance stability, and unexplained transfers.',
  },
  'Paystub': {
    status: 'Income Support Review',
    confidence: '74%',
    sections: [
      ['Employer', 'Employer name should match application and employment verification.'],
      ['Pay Frequency', 'Pay cycle appears consistent with stated income cadence.'],
      ['Gross / Net Pay', 'Use gross income for policy rules only when the policy allows it.'],
      ['YTD Consistency', 'Year-to-date earnings should make sense against current pay period.'],
      ['Document Quality', 'Review formatting, deductions, and tax fields for missing or inconsistent data.'],
    ],
    notes: ['A paystub supports income, but it should not stand alone for higher-risk credit decisions.', 'Compare with bank deposits and employer confirmation when risk is elevated.'],
    tip: 'Paystub reviews are about consistency. Employer, pay dates, deposits, and YTD math should all tell the same story.',
  },
  'Police Report': {
    status: 'External Claim Support',
    confidence: '69%',
    sections: [
      ['Report Number', 'Report reference is present and tied to the claimed event.'],
      ['Filed Date', 'Filed date should make sense against loss date and first customer contact.'],
      ['Narrative', 'Narrative describes the loss type but may not independently prove fraud.'],
      ['Jurisdiction', 'Agency location should align with the customer or incident location.'],
      ['Follow-Up Needed', 'Confirm report authenticity if policy requires direct verification.'],
    ],
    notes: ['Police reports can support a customer statement, but they often rely on what the customer reported.', 'Use this with login, device, shipping, or transaction evidence.'],
    tip: 'A police report is supporting evidence. It is helpful, but the strongest decision still comes from matching it to internal records.',
  },
  'Merchant Receipt': {
    status: 'Merchant Packet Review',
    confidence: '81%',
    sections: [
      ['Receipt Match', 'Amount and merchant name match the disputed transaction.'],
      ['Purchase Channel', 'Review whether transaction was in-store, online, keyed, or wallet-based.'],
      ['Customer Details', 'Email, phone, shipping, or loyalty details may connect the cardholder to the order.'],
      ['Fulfillment', 'Receipt references fulfillment details that should match shipping or pickup records.'],
      ['Policy Signal', 'Receipt quality affects chargeback representment strength.'],
    ],
    notes: ['Compare with Authorization Log and Order Match Sheet.', 'For chargebacks, merchant evidence must fit the dispute reason code.'],
    tip: 'Merchant receipts are not just proof of a sale. They should help prove who participated and whether goods or services were provided.',
  },
  'Business License': {
    status: 'KYB Support Review',
    confidence: '80%',
    sections: [
      ['Business Name', 'Legal or DBA name should match application records.'],
      ['Registration Status', 'License appears active in the fictional review record.'],
      ['Address', 'Business address should line up with KYB, website, and bank application data.'],
      ['Ownership Clue', 'Owner or officer details require comparison with beneficial owner records.'],
      ['Business Activity', 'Industry should make sense for expected payroll, ACH, or payment behavior.'],
    ],
    notes: ['Business License supports existence, not necessarily legitimacy or repayment ability.', 'Pair this with secretary-of-state data, website review, bank statements, and negative news.'],
    tip: 'KYB reviews need layers. A real business can still create risk if ownership, activity, or funding behavior does not line up.',
  },
  'Authorization Log': {
    status: 'Card Authorization Review',
    confidence: '85%',
    sections: [
      ['Auth Result', 'Authorization approved with normal issuer response code.'],
      ['Entry Method', 'Review chip, magstripe, keyed, ecommerce, wallet, or tokenized entry.'],
      ['AVS / CVV', 'Address and security-code response should support or weaken merchant position.'],
      ['Device / Token', 'Token or device data may connect the transaction to prior customer behavior.'],
      ['Timing', 'Authorization time should align with merchant receipt and customer claim timeline.'],
    ],
    notes: ['Authorization approval does not automatically mean cardholder participation.', 'For chargebacks, compare entry method and authentication to the claim reason.'],
    tip: 'Authorization logs answer how the payment was approved. They do not answer the full fraud question without context.',
  },
  'Order Match Sheet': {
    status: 'Order Identity Match',
    confidence: '83%',
    sections: [
      ['Name Match', 'Order name should be compared against Customer 360 and shipping records.'],
      ['Email / Phone', 'Contact details may match the customer or show a suspicious alternate.'],
      ['Billing Address', 'Billing data should match issuer records or show explainable differences.'],
      ['Shipping Address', 'Shipping location should be checked for household, reshipper, or prior-claim links.'],
      ['Device / IP', 'Order device and IP should be compared with Identity Intel and Device Fingerprint.'],
    ],
    notes: ['A strong order match can support merchant liability defense or first-party fraud concerns.', 'Weak matches should trigger customer interview and additional documents.'],
    tip: 'Order matching is about identity overlap. The more fields that independently align, the stronger the participation signal.',
  },
  'Payment Timeline': {
    status: 'Money Movement Timeline',
    confidence: '90%',
    sections: [
      ['Instruction Change', 'Payment details changed shortly before the disputed transfer.'],
      ['Approval Path', 'Review who approved, what controls fired, and whether callback was completed.'],
      ['Beneficiary', 'Beneficiary appears new or materially changed from historical payments.'],
      ['Release Time', 'Funds released after the suspicious communication window.'],
      ['Recovery Window', 'Escalation timing affects recall, return, or recovery chances.'],
    ],
    notes: ['For BEC and wire-style cases, timeline order is the core evidence.', 'Compare Payment Timeline with Email Header and Beneficiary Review.'],
    tip: 'Payment timelines show whether the loss followed a control break. Sequence matters more than any single event.',
  },
  'Carrier Timeline': {
    status: 'Shipment Movement Review',
    confidence: '84%',
    sections: [
      ['Label Created', 'Label timing should match merchant order and fulfillment records.'],
      ['Origin Scan', 'Origin scan supports shipment handoff to carrier.'],
      ['In-Transit Events', 'Movement history should not contain unexplained reroutes or gaps.'],
      ['Delivery Scan', 'Delivery scan should align with Proof of Delivery and delivery address.'],
      ['Exception Events', 'Hold, redirect, damaged, or pickup events require closer review.'],
    ],
    notes: ['Use Carrier Timeline with Proof of Delivery for non-receipt disputes.', 'A delivered scan is stronger when paired with GPS, photo, or signature evidence.'],
    tip: 'Carrier timelines are useful because they show movement, but delivery context decides how much weight to give them.',
  },
  'Prior Claims Memo': {
    status: 'Claim Pattern Review',
    confidence: '79%',
    sections: [
      ['Prior Volume', 'Review count of prior claims across digital access, card, delivery, and credit products.'],
      ['Claim Themes', 'Repeated non-receipt, unauthorized access, or merchant dispute themes may indicate pattern risk.'],
      ['Outcome History', 'Compare approvals, denials, withdrawals, and missing-document closures.'],
      ['Timing Pattern', 'Look for claims clustered near large purchases, account changes, or credit stress.'],
      ['Policy Note', 'Prior claims should inform risk, not replace evidence for the current case.'],
    ],
    notes: ['Prior claims can be a red flag, but each case still needs current evidence.', 'Use this memo carefully so the decision remains evidence-based and fair.'],
    tip: 'Pattern evidence is seasoning, not the meal. It adds context after current-case facts are reviewed.',
  },
  'Device Fingerprint Report': {
    status: 'High Risk',
    confidence: '34%',
    sections: [
      ['Device ID', 'First seen today; not previously trusted on this profile.'],
      ['Device Type', 'Android mobile browser with a new browser fingerprint.'],
      ['Known Device', 'No. Customer profile normally uses a different trusted device.'],
      ['Location Velocity', 'New access location conflicts with expected customer geography.'],
      ['Risk Signals', 'New device, profile change, and transaction activity occurred in the same short window.'],
    ],
    notes: ['Compare this report against Login Timeline and MFA History.', 'Ask customer whether anyone requested a security code or device approval.'],
    tip: 'Device reports matter most when they are compared to timing. A new device is suspicious, but a new device plus password reset plus money movement is much stronger.',
  },
  'Login Timeline': {
    status: 'Authentication Review',
    confidence: '88%',
    sections: [
      ['8:38 AM', 'Three failed login attempts from a new browser/device pairing.'],
      ['8:41 AM', 'Successful login from a new device and new network.'],
      ['Device / Browser', 'Android mobile browser, first seen on this profile.'],
      ['Network', 'New IP address outside the customer normal pattern.'],
      ['Session End', 'No normal logout event captured.'],
    ],
    notes: ['Login Timeline should show authentication events only: success, failure, device, network, browser, operating system, session start, and logout.', 'Open Profile Change History to see what account details changed after login.'],
    tip: 'Login history answers: who accessed the account, from where, on what device, and whether the access pattern was normal. It should not be the only place profile changes live.',
  },
  'Profile Change History': {
    status: 'Account Control Risk',
    confidence: '93%',
    sections: [
      ['Password', 'Changed one minute after the new-device login.'],
      ['Recovery Email', 'Updated during the same session.'],
      ['Phone Number', 'Changed before OTP delivery.'],
      ['MFA Device', 'New SMS route enrolled.'],
      ['Security Questions', 'Updated after password reset.'],
    ],
    notes: ['This report belongs with account/client history because it shows account maintenance changes, not login attempts.', 'Multiple security settings changed within minutes is a strong ATO control pattern.'],
    tip: 'Profile Change History answers: what changed on the account, when it changed, and whether those changes gave someone control of the account.',
  },
  'Session History': {
    status: 'Post-Login Activity Review',
    confidence: '87%',
    sections: [
      ['Session Start', '8:41 AM after new-device authentication.'],
      ['Pages Viewed', 'Security settings, profile, transfer, and card controls.'],
      ['Actions Taken', 'Contact method changed, MFA route changed, then transaction path opened.'],
      ['Money Movement', 'Disputed transaction or transfer initiated after account-control changes.'],
      ['Logout', 'No normal logout event captured.'],
    ],
    notes: ['Session History answers what happened after the login.', 'Use it to connect authentication, profile maintenance, payee/token activity, and money movement in order.'],
    tip: 'Session history is the bridge between Login History and Transaction Timeline. It shows whether the user simply viewed the account or moved toward control and loss.',
  },
  'MFA History': {
    status: 'Control Break',
    confidence: '82%',
    sections: [
      ['OTP Delivery', 'Code sent to a newly added or recently changed contact method.'],
      ['Challenge Result', 'Passed on first attempt.'],
      ['Customer Recognition', 'Customer denies approving new authentication setup.'],
      ['Risk Concern', 'MFA may have been bypassed through social engineering rather than technical failure.'],
    ],
    notes: ['Check whether the customer received a spoofed call or text.', 'Compare MFA event time against password reset and device enrollment.'],
    tip: 'A passed OTP does not always mean the customer authorized the activity. Social engineering can make bad activity look authenticated.',
  },
  'IP Lookup': {
    status: 'Network Mismatch',
    confidence: '76%',
    sections: [
      ['IP Address', 'New network not seen on this customer profile before.'],
      ['Geo Signal', 'Location differs from normal customer region.'],
      ['Network Type', 'Residential or proxy-like signal requires comparison with device history.'],
      ['Velocity', 'Travel pattern is unlikely based on previous login timing.'],
    ],
    notes: ['Do not rely on IP alone. Compare against device, customer interview, and transaction timing.'],
    tip: 'IP data is a supporting clue. It gets stronger when it lines up with other suspicious changes.',
  },
  'Proof of Delivery': {
    status: 'Merchant Support',
    confidence: '88%',
    sections: [
      ['Delivery Address', 'Matches billing or verified customer address.'],
      ['GPS / Scan', 'Carrier scan is near the expected delivery location.'],
      ['Photo / Signature', 'Delivery image or signature supports merchant position.'],
      ['Claim Pattern', 'Compare with prior non-receipt disputes before deciding.'],
    ],
    notes: ['Strong delivery proof can support denial in first-party fraud, but still review household access and merchant packet quality.'],
    tip: 'For non-receipt claims, proof of delivery plus repeated claim behavior can be stronger than either clue alone.',
  },
  'Email Header': {
    status: 'Spoofing Indicators',
    confidence: '89%',
    sections: [
      ['Sender Domain', 'Lookalike or newly registered sender domain.'],
      ['Authentication', 'SPF/DKIM/DMARC mismatch or missing authentication.'],
      ['Thread Context', 'Language copied from a legitimate vendor thread.'],
      ['Payment Change', 'Bank instructions changed without callback verification.'],
    ],
    notes: ['Confirm whether the beneficiary was new and whether callback controls were followed.'],
    tip: 'BEC reviews are about process failure and payment-change verification, not just whether the email looked real.',
  },
};

export function getDocumentReport(name, caseData) {
  const fallback = {
    status: caseData.risk === 'High' ? 'Needs Review' : 'Mostly Consistent',
    confidence: caseData.risk === 'High' ? '62%' : '84%',
    sections: [
      ['Customer', caseData.customer],
      ['Case ID', caseData.id],
      ['Claim Type', caseData.type],
      ['Record Signal', caseData.risk === 'High' ? 'Contains mismatch, missing support, or timeline issue.' : 'Mostly matches the claim record but still needs comparison.'],
    ],
    notes: ['Compare this document with Toolkit results, Customer 360, and Interview answers.'],
    tip: 'A document is strongest when it confirms or contradicts another piece of evidence.',
  };

  return reportDetails[name] || fallback;
}
